# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/sarabjot/Downloads/website/osg/vcpkg/buildtrees/osg/src/raph-3.6.4-7f0089ee03/paras/simpleCmake

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/sarabjot/Downloads/website/osg/vcpkg/buildtrees/osg/src/raph-3.6.4-7f0089ee03/paras/simpleCmake

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sarabjot/Downloads/website/osg/vcpkg/buildtrees/osg/src/raph-3.6.4-7f0089ee03/paras/simpleCmake/CMakeFiles /home/sarabjot/Downloads/website/osg/vcpkg/buildtrees/osg/src/raph-3.6.4-7f0089ee03/paras/simpleCmake/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/sarabjot/Downloads/website/osg/vcpkg/buildtrees/osg/src/raph-3.6.4-7f0089ee03/paras/simpleCmake/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named animalSim

# Build rule for target.
animalSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 animalSim
.PHONY : animalSim

# fast build rule for target.
animalSim/fast:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/build
.PHONY : animalSim/fast

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/main.cpp.s
.PHONY : main.cpp.s

src/animals/funcs.o: src/animals/funcs.cpp.o

.PHONY : src/animals/funcs.o

# target to build an object file
src/animals/funcs.cpp.o:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/src/animals/funcs.cpp.o
.PHONY : src/animals/funcs.cpp.o

src/animals/funcs.i: src/animals/funcs.cpp.i

.PHONY : src/animals/funcs.i

# target to preprocess a source file
src/animals/funcs.cpp.i:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/src/animals/funcs.cpp.i
.PHONY : src/animals/funcs.cpp.i

src/animals/funcs.s: src/animals/funcs.cpp.s

.PHONY : src/animals/funcs.s

# target to generate assembly for a file
src/animals/funcs.cpp.s:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/src/animals/funcs.cpp.s
.PHONY : src/animals/funcs.cpp.s

src/animals/horse.o: src/animals/horse.cpp.o

.PHONY : src/animals/horse.o

# target to build an object file
src/animals/horse.cpp.o:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/src/animals/horse.cpp.o
.PHONY : src/animals/horse.cpp.o

src/animals/horse.i: src/animals/horse.cpp.i

.PHONY : src/animals/horse.i

# target to preprocess a source file
src/animals/horse.cpp.i:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/src/animals/horse.cpp.i
.PHONY : src/animals/horse.cpp.i

src/animals/horse.s: src/animals/horse.cpp.s

.PHONY : src/animals/horse.s

# target to generate assembly for a file
src/animals/horse.cpp.s:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/src/animals/horse.cpp.s
.PHONY : src/animals/horse.cpp.s

src/animals/mule.o: src/animals/mule.cpp.o

.PHONY : src/animals/mule.o

# target to build an object file
src/animals/mule.cpp.o:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/src/animals/mule.cpp.o
.PHONY : src/animals/mule.cpp.o

src/animals/mule.i: src/animals/mule.cpp.i

.PHONY : src/animals/mule.i

# target to preprocess a source file
src/animals/mule.cpp.i:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/src/animals/mule.cpp.i
.PHONY : src/animals/mule.cpp.i

src/animals/mule.s: src/animals/mule.cpp.s

.PHONY : src/animals/mule.s

# target to generate assembly for a file
src/animals/mule.cpp.s:
	$(MAKE) -f CMakeFiles/animalSim.dir/build.make CMakeFiles/animalSim.dir/src/animals/mule.cpp.s
.PHONY : src/animals/mule.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... animalSim"
	@echo "... edit_cache"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... src/animals/funcs.o"
	@echo "... src/animals/funcs.i"
	@echo "... src/animals/funcs.s"
	@echo "... src/animals/horse.o"
	@echo "... src/animals/horse.i"
	@echo "... src/animals/horse.s"
	@echo "... src/animals/mule.o"
	@echo "... src/animals/mule.i"
	@echo "... src/animals/mule.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

